In [40]:
import csv
with open("data.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Name", "Age", "City"])
    writer.writerow(["Roshini","20","Anakapalli"])
    writer.writerow(["Rupesh","19","kakinada"])

In [41]:
import csv
with open("data.csv", "r") as file:
    reader=csv.reader(file)
    for row in reader:
        print(reader)
    

In [42]:
import numpy as np

In [43]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [44]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
l=range(1000)
%timeit [i**2 for i in l]

285 μs ± 28.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [46]:
a=np.arange(1000)
%timeit a**2

4.33 μs ± 719 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# CREATING ARRAYS

In [47]:
a = np.array([1,2,3,4])

In [48]:
print(a.ndim)

1


In [49]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [50]:
print(b.ndim)

2


In [51]:
c = np.array([[[1,2],[3,4],[5,6],[7,6]]])

In [52]:
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 6]]]


In [53]:
print(c.ndim)

3


In [54]:
print(a.shape)

(4,)


In [55]:
print(b.shape)

(2, 3)


In [56]:
print(c.shape)

(1, 4, 2)


## FUNCTIONS FOR CREATING ARRAY

In [57]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [59]:
a = np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [60]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [61]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [62]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [63]:
a = np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [64]:
a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [65]:
print(np.diag(a))

[1 2 3 4]


## BASIC DATATYPES

In [66]:
a = np.arange(10)
print(a.dtype)

int64


In [67]:
a = np.arange(10,dtype="float64")
print(a.dtype)

float64


In [68]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


## OTHER DATA TYPES

In [69]:
a = np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [70]:
a = np.array([True,False])
print(a.dtype)

bool


In [71]:
a = np.array(['Roshini','Rupesh'])
print(a.dtype)

<U7


## INDEXING AND SLICING

In [72]:
a = np.arange(10)
print(a[5])

5


In [73]:
a = np.diag([1,2,3])
print(a[2,2])

3


In [74]:
a[2,1] = 5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


## SLICING

In [75]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [76]:
print(a[1:8:2])

[1 3 5 7]


In [78]:
a = np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

## COPIES AND VIEWING

In [79]:
a = np.arange(10)
b = a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [80]:
print(np.shares_memory(a,b))

True


In [81]:
b[0] = 10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [82]:
a = np.arange(10)
b = a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [83]:
print(np.shares_memory(a,b))

False


In [85]:
b[0] = 10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


## RANDOM NUMBER GENERATOR

In [86]:
a = np.random.randint(0,20,15)
print(a)

[11 19 13 18 10 19 13 10  2  0 10 14 15 14  0]


In [87]:
mask=(a%2==0)

In [88]:
mask_a = a[mask]
print(mask_a)

[18 10 10  2  0 10 14 14  0]


In [89]:
a[mask] = -1
print(a)

[11 19 13 -1 -1 19 13 -1 -1 -1 -1 -1 15 -1 -1]


## ELEMENT WISE OPERATIONS

1.BASIC OPERATIONS

In [90]:
a = np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [91]:
print(a**2)

[ 1  4  9 16]


# ALL ARITHEIMETIC OPERATIONS ELEMENT WISE

In [92]:
b = np.ones(4) + 1
print("a = ",a)
print("b = ",b)

a =  [1 2 3 4]
b =  [2. 2. 2. 2.]


In [93]:
print(a*b)

[2. 4. 6. 8.]


In [94]:
print(a-b)

[-1.  0.  1.  2.]


In [95]:
c = np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [96]:
print(c * c)
print("************************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


# COMPARISION OPERATORS

In [97]:
a = np.array([1,2,3,4])
b = np.array([5,2,7,4])
print(a==b)

[False  True False  True]


In [98]:
print(a<b)

[ True False  True False]


In [99]:
print(a>b)

[False False False False]


In [100]:
print(a<=b)

[ True  True  True  True]


In [101]:
print(a>=b)

[False  True False  True]


In [102]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [103]:
print(np.array_equal(a,c))

True


# LOGICAL OPERATORS

In [104]:
a = np.array([1,0,1,0],dtype = "bool")
a = np.array([1,1,0,0],dtype = "bool")

In [105]:
print(np.logical_or(a,b))

[ True  True  True  True]


In [106]:
print(np.logical_and(a,b))

[ True  True False False]


# TRIGONOMETRY/TRANCENDENTAL FUNCTIONS

In [108]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [109]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [110]:
np.log(a)

C:\Users\Admin\AppData\Local\Temp\ipykernel_13836\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])